### PR TITLE
fix: set autocomplete=off in assign project lead input

### PR DESCRIPTION
**Pull request by HaiDang666**
- [x ] Unit tests
- [x ] Tests with Cypress 
- [ ] Documentation
- [ ] Dummy data

When searching for employee to assign, an autocomplete will show up and block the search result, thus users have to click in the outerspace to close it.

Screen Shot 2021-02-20 at 9 00 28 pm

### CODE REVIEW

**Comment by djaiss** [comment]
To be honest I didn't expect anyone to contribute considering the state of the project. It’s not even launched yet and the repository is not really ready for external contributors.

That being said, thanks so much for taking the time to understand the product and try to make it better. The project is not yet ready for prime time, but every help helps!

So, thanks!

**Comment by HaiDang666** [comment]
> To be honest I didn't expect anyone to contribute considering the state of the project. It’s not even launched yet and the repository is not really ready for external contributors.
> 
> That being said, thanks so much for taking the time to understand the product and try to make it better. The project is not yet ready for prime time, but every help helps!
> 
> So, thanks!

Oh sorry for the inconvenience, I just thought it is good for me to follow from the beginning. Again, sorry for it but If you need a hand for doing little stuff, I'd like to help.

**Comment by djaiss** [comment]
> Oh sorry for the inconvenience, I just thought it is good for me to follow from the beginning. Again, sorry for it but If you need a hand for doing little stuff, I'd like to help.

No problem at all. In fact, I would like to thank you very, very much for taking the time to setup the project and start to play with it.

Did you enjoy your experience so far?

**Comment by HaiDang666** [comment]
> > Oh sorry for the inconvenience, I just thought it is good for me to follow from the beginning. Again, sorry for it but If you need a hand for doing little stuff, I'd like to help.
> 
> No problem at all. In fact, I would like to thank you very, very much for taking the time to setup the project and start to play with it.
> 
> Did you enjoy your experience so far?

Sure. I've learned new stuff in both design structure and supporting tools which I definitely use in the future.

**Pull request merged**
