### PR TITLE
chore: change coverage settings

### PR DESCRIPTION
**Pull request by asbiin**
### Tests on SQLite
| | without coverage | with coverage |
|---|---|---|
| Unit test | 30s | 3min |
| Integration test | 1min |

### Tests on Mysql
| | without coverage | with coverage |
|---|---|---|
| Unit test | 55s | 1min45s |
| Integration test | 2min35s |

We could run

    unit test on mysql with code coverage (=1min45sec)
    unit test and integration test with sqlite (without code coverage) (=2min10sec total)

integration test will not run with mysql (anyway, they are just test for command which will never run on production)

### CODE REVIEW

**Comment by asbiin** [comment]
We could run
- unit test on mysql with code coverage (=1min45sec)
- unit test and integration test with sqlite (without code coverage) (=2min10sec total)

integration test will not run with mysql (anyway, they are just test for command which will never run on production)

**Comment by djaiss** [comment]
@asbiin are you sure of these numbers? SQlite tests should be 10x times faster than MySQL, especially without coverage.

**Comment by asbiin** [comment]
@djaiss I did not do a deep analysis on the numbers, but that's some metrics I got from the running jobs of this PR and the main branch

**Comment by asbiin** [comment]
@djaiss I've rerun and unit tests with sqlite take 30 sec now ;)

**Pull request merged**
