### PR TITLE
feat: create project from timesheet link

### PR DESCRIPTION
**Pull request by asbiin**
When there is no project, and you want to create a timesheet, there is a link 'create a project' which does not work.

You fool, don't forget these steps:

- [ ] Unit tests
- [ ] Tests with Cypress
- [ ] Documentation
- [ ] Dummy data

### CODE REVIEW

**Comment by djaiss** [comment]
I'll check this tomorrow for sure. Too late tonight.

**Comment by asbiin** [comment]
I have a doubt
I wanted to create such workflow:
Timesheet -> clic on link -> Create project (new page for this scenario) -> Timesheet
But to be able to create a timesheet for a project, you need to be added to it, and a task need to be created.

So either
- after creating the project, we can stay on the project's page, so the person can add informations, names, tasks
- or we add the creator as a project's member, and make the task creation more easy.

What do you think?

**Comment by djaiss** [comment]
>  But to be able to create a timesheet for a project, you need to be added to it, and a task need to be created.

Interesting idea.
I think the easiest solution here would be:
- we create the project
- the creator of the project becomes automatically part of the project
- it's then up to him/her to create a task etc... and log his time.

**Comment by asbiin** [comment]
> it's then up to him/her to create a task etc... and log his time.

So it will require some UI in the Timesheet context to create a new task ...

**Pull request closed without merging**
